In [1]:
#FUNDAMENTAL CONCEPTS OF TENSORS USING TENSORFLOW

In [2]:
#Import Tensorflow
import tensorflow as tf
print(tf.__version__)


2.8.2


In [17]:
#Creating tensors with tf.constant ()
scalar = tf.constant (7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#check the number of dimensions of a tensor ndim
scalar.ndim


0

In [5]:
#create a vector
vector = [ tf.constant ([10,10])]
vector

[<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>]

In [6]:
#create dimension of vector
vector = tf.constant ([10,10])
vector.ndim


1

In [7]:
#create a matrix
matrix = tf.constant([[10, 7], [ 7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
#Create another matrix
another_matrix = tf.constant ([[10.,7.],[3., 2.], [8.,9.]], dtype =tf.float16) #specify data type with dtype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
#ndim of another matrix
another_matrix.ndim

2

In [19]:
#Creating a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [20]:
tensor.ndim

3

In [13]:
#What we have done
#scalar is a single number
#vector: a number with direction
#matrix: 2 dimensional array
#tensor: n-dimensional array of number where n can be any number.

In [14]:
#Creating Tensors woth tf.variable
changeable_tensor = tf.Variable ([10, 7])
unchangeable_tensor = tf.constant ([10,7])
changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [15]:
#Changing one of the elements in the chnageable tensor
changeable_tensor [0]=7
changeable_tensor

TypeError: ignored

In [ ]:
#How to change the elements of a tensor

In [21]:
changeable_tensor [0].assign(7)
changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#Changing our unchangeable tensor
unchangeable_tensor [0].assign(7)
unchangeable_tensor

In [22]:
#Creating randome tensors
#Tensors of an arbitrary size containing random numbers
#creating two random but the same tensors
random_1 = tf.random.Generator.from_seed(7)#set seed for reproducablity
random_1 = random_1.normal (shape=(3, 2))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal (shape=(3, 2))

#Are they equal?
random_1, random_2, random_1 ==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [38]:
### shuffle the order of elements ina tensor (valuable when you want to shuffle your data so that order does not affect learning)
not_shuffled = tf.constant ([[10, 7],[3,4], [2,5]])
not_shuffled.ndim
not_shuffled
#shuffle ornon shuffled tensor
tf.random.set_seed (42) #global level random seed
shuffled = tf.random.shuffle(not_shuffled, seed = 42) #operation level random seed
shuffled


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

Read through tensorflow documnetation on random seed genereation.
Rule:  If we want our shuffled tensors to be in the same order we use both the global and operation level seed. 

In [44]:
#Other ways to make tensors
tf.ones ([10, 7])


<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [39]:
tf.zeros (shape = (3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [45]:
#Turn Numpy Arrays into tensors
import numpy as np
numpy_A = np.arange (1, 25, dtype = np.int32) #creat a numpy array between 1 and 25
numpy_A
#A CAPITAL for matrix or tensor
#a small for a vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [51]:
A = tf.constant (numpy_A, shape = (2,4,3))
B = tf.constant (numpy_A)
A, B

(<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [54]:
#GETTING INFORMATION FROM TENSORS
#sHAPE
#Rank
#Axis
#Size (total number of elements)

#cREAT A RANK 4 TENSOR
rank_4_tensor=tf.ones(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [55]:
rank_4_tensor[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

In [56]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [57]:
rank_4_tensor.ndim

4

In [60]:
tf.size(rank_4_tensor)
tf.size(rank_4_tensor).numpy()

120

In [61]:
rank_4_tensor.dtype

tf.float32

##Indexing a Tensor

In [66]:
#Get the first 2 elements oof each dimention
rank_4_tensor[:2,:2,:2,:]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]], dtype=float32)>

In [89]:
#Last Element of Each Row
rank_2_tensor =tf.constant([[2,3,4,],
                            [7,4,9],
                            [3,8,2]], dtype=float)
rank_2_tensor[:, -1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 9., 2.], dtype=float32)>

In [95]:
#Expand Dimensions of a Tensor to make rank 2 into a rank 3 tensor
rank_3_tensor=tf.expand_dims(rank_2_tensor,axis=-1)
rank_3_tensor

<tf.Tensor: shape=(3, 3, 1), dtype=float32, numpy=
array([[[2.],
        [3.],
        [4.]],

       [[7.],
        [4.],
        [9.]],

       [[3.],
        [8.],
        [2.]]], dtype=float32)>

In [4]:
#Manipulating Tensors

##Basic Operations of Tensors

In [5]:
#Addition
tensor =tf.constant([[2,4],[3,10]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 14],
       [13, 20]], dtype=int32)>

In [6]:
#Multiplication
tensor*5
tf.multiply(tensor,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [15, 50]], dtype=int32)>

In [7]:
#Subtraction
tensor-1


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 9]], dtype=int32)>

In [8]:
#Division
tensor/2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 2. ],
       [1.5, 5. ]])>

In [9]:
#MatMul in TensorFlow (Dot Prodct)
print(tensor)
tf.matmul(tensor,tensor)


tf.Tensor(
[[ 2  4]
 [ 3 10]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 16,  48],
       [ 36, 112]], dtype=int32)>

In [10]:
#Elementwise matrix multiplication
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  4,  16],
       [  9, 100]], dtype=int32)>

You can always use the tensorlfow reshape function (tf.reshape(tensor, shape=2, 3) to ensure that the dimensions of the matrices are compatible when multiplying

In [28]:
import tensorflow as tf
import numpy as np
#Transposing swaps rows for columns and columns for rows
tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  3],
       [ 4, 10]], dtype=int32)>

In [12]:
A = tf.constant([[3, 5],
                 [7,10],
                  [8,3]])
B =tf.constant([[3,8],
               [7,9],
                ])
print(A@B)

tf.Tensor(
[[ 44  69]
 [ 91 146]
 [ 45  91]], shape=(3, 2), dtype=int32)


#The Dot Product
#Matrix Multiplication Can be performed using:
#tf.matmul()
#tf.tensordot()

In [13]:
tf.matmul(A,B)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 44,  69],
       [ 91, 146],
       [ 45,  91]], dtype=int32)>

#tf.matmul(A,B)==A@B


In [14]:
tf.tensordot(A,B, axes=0) #If axes=0, the results is that of a dot product, while if the azes=1, the result is that of a matmul (A@B)

<tf.Tensor: shape=(3, 2, 2, 2), dtype=int32, numpy=
array([[[[ 9, 24],
         [21, 27]],

        [[15, 40],
         [35, 45]]],


       [[[21, 56],
         [49, 63]],

        [[30, 80],
         [70, 90]]],


       [[[24, 64],
         [56, 72]],

        [[ 9, 24],
         [21, 27]]]], dtype=int32)>

##For the multiplacation of tensors to vbe successful, we may have to transpose and reshape the tensors (read matrices). When do you transpose and when do you reshape?

In [15]:
#Generally when performing matrix multiplication on two tensors and one of the axes dont line up, you will traspose rather than reshape one of the tensors to satisty matmul rules

#Change Datatype of a Tensor

In [18]:
tensor_T=tf.constant([[3.,5.],
                      [7.,4.],
                      [9.,8.]])
tensor_T

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 5.],
       [7., 4.],
       [9., 8.]], dtype=float32)>

In [21]:
#Performs reduced Precision by changing the dtype of tensor_T from float32 to float16
D = tf.cast(tensor_T, dtype=tf.float16)
D

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[3., 5.],
       [7., 4.],
       [9., 8.]], dtype=float16)>

##Aggregating Tensors

In [23]:
K = tf.constant([[3,5],
                 [-4,-9],
                 [-2,-8]])
K

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  5],
       [-4, -9],
       [-2, -8]], dtype=int32)>

In [25]:
#finding the absolute value of a tensor
K_1= tf.abs(K)
K_1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [4, 9],
       [2, 8]], dtype=int32)>

# Create a Random tensor with valyes between 0 and 100

In [30]:
F = tf.constant(np.random.randint(0,100, size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 1, 83, 21, 40, 53, 53, 73, 32, 11, 11, 82, 11, 67, 14, 22,  3, 93,
       53, 55, 77, 42, 81, 61,  0, 31,  2, 96,  4, 80, 33,  7, 25, 34, 31,
       58, 87, 94, 84, 80, 53, 38, 82, 21,  3, 26, 50, 88,  8, 57,  1])>

In [32]:
F.ndim, F.shape, tf.size(F)

(1, TensorShape([50]), <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [36]:
#Finding the max, min and sum
min = tf.reduce_min(F)
min

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [37]:
max = tf.reduce_max (F)
max

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [57]:
sum = tf.reduce_sum(F)
sum.numpy()

2212

In [56]:
mean = tf.reduce_mean(F)
mean.numpy()

44

In [55]:
#std
sd =tf.math.reduce_std(tf.cast(F, dtype=tf.float32))
sd.numpy()

30.701506

In [54]:
#to find variance we need access to tensorflow probability
#Can also be done as with the std above
import tensorflow_probability as tfp
variance = tfp.stats.variance (F)
variance

<tf.Tensor: shape=(), dtype=int64, numpy=942>

##Find the Positional Maximum and minimum of a tensor

In [67]:
tf.random.set_seed(42)
G = tf.random.uniform(shape=[50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [68]:
#Positional Max
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [69]:
#Index largest position
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [70]:
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [71]:
tf.reduce_max(G)==G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [72]:
#pOSITIONAL MINIMUM
tf.argmin(G)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [75]:
#Squeeze a Tensor: Remove diemsions of size 1 from the shape of a tensor
tf.random.set_seed(42)
G = tf.random.uniform(shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [76]:
g_squeezed= tf.squeeze(G)
g_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [87]:
#ONE-HOT ENCODING TENSORS

some_list=[0,1,2,3]
depth=4
tf.one_hot(some_list,depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [85]:
#Specify Custom Values for 1 hot encoding
some_list=[0,1,2,3]
depth=4
tf.one_hot(some_list,depth, on_value='Yes',off_value='No')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

#Square, Log and Square Root

In [95]:
#Create a new tensor
L=tf.range(1,10)
L

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [96]:
#Square
tf.square(L)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [98]:
#sQUAREROOT (METHOD REQUIRES NON-INT32 TYPE)
tf.sqrt(tf.cast(L, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [102]:
#Find the Log
tf.math.log(tf.cast(L, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

##Tensors and Numpy


1.   TF interacts beautifuly with np
2.   they work together nicely



In [103]:
J = tf.constant(np.array([1,2,3,4,5,6,7]))
J

<tf.Tensor: shape=(7,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6, 7])>

In [105]:
#cONVERT TENSOR BACK TO NP 
np.array(J), type(np.array(J))

(array([1, 2, 3, 4, 5, 6, 7]), numpy.ndarray)